version: "3.8"

services:
  platform-server:
    container_name: platform-server
    build:
      context: .
      dockerfile: platform.Dockerfile
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .platform.dev.env
    depends_on:
      - db
      - redis
    command: npm run start:prod

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    env_file:
      - .platform.dev.env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
volumes:
  db_data:

