version: "3.8"

services:
  platform-server:
    container_name: platform-server
    build:
      context: .
      dockerfile: platform.Dockerfile
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    command: npm run start:prod