export const HTTP_CLIENT_TOKENS = {
  SWING_ANALYZER: 'SWING_ANALYZER',
  LLM_GATEWAY: 'LLM_GATEWAY',
  KAKAO: 'KAKAO',
  IP_LOCATION: 'IP_LOCATION',
  GOOGLE_CALENDAR: 'GOOGLE_CALENDAR',
  OPENAI: 'OPENAI',
} as const;

export type HttpClientToken =
  (typeof HTTP_CLIENT_TOKENS)[keyof typeof HTTP_CLIENT_TOKENS];
